"""empty message

Revision ID: 4a6a6309069f
Revises: 
Create Date: 2018-04-10 09:46:25.770936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a6a6309069f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gebruiker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('naam', sa.String(length=64), nullable=True),
    sa.Column('gebruikersnaam', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gebruiker_gebruikersnaam'), 'gebruiker', ['gebruikersnaam'], unique=True)
    op.create_index(op.f('ix_gebruiker_naam'), 'gebruiker', ['naam'], unique=True)
    op.create_table('ploeg',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ploegnaam', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ploeg_ploegnaam'), 'ploeg', ['ploegnaam'], unique=True)
    op.create_table('speler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('naam', sa.String(length=64), nullable=True),
    sa.Column('voornaam', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_speler_naam'), 'speler', ['naam'], unique=True)
    op.create_index(op.f('ix_speler_voornaam'), 'speler', ['voornaam'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_speler_voornaam'), table_name='speler')
    op.drop_index(op.f('ix_speler_naam'), table_name='speler')
    op.drop_table('speler')
    op.drop_index(op.f('ix_ploeg_ploegnaam'), table_name='ploeg')
    op.drop_table('ploeg')
    op.drop_index(op.f('ix_gebruiker_naam'), table_name='gebruiker')
    op.drop_index(op.f('ix_gebruiker_gebruikersnaam'), table_name='gebruiker')
    op.drop_table('gebruiker')
    # ### end Alembic commands ###
