"""empty message

Revision ID: 6668ad6b514e
Revises: 
Create Date: 2018-04-11 20:28:07.223575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6668ad6b514e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gebruiker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('naam', sa.String(length=64), nullable=True),
    sa.Column('gebruikersnaam', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('rechten', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gebruiker_gebruikersnaam'), 'gebruiker', ['gebruikersnaam'], unique=True)
    op.create_index(op.f('ix_gebruiker_naam'), 'gebruiker', ['naam'], unique=True)
    op.create_table('ploeg',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ploegnaam', sa.String(length=64), nullable=True),
    sa.Column('seizoen', sa.String(length=32), nullable=True),
    sa.Column('reeks', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ploeg_ploegnaam'), 'ploeg', ['ploegnaam'], unique=True)
    op.create_index(op.f('ix_ploeg_reeks'), 'ploeg', ['reeks'], unique=False)
    op.create_index(op.f('ix_ploeg_seizoen'), 'ploeg', ['seizoen'], unique=False)
    op.create_table('speler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('groupcode', sa.String(length=128), nullable=True),
    sa.Column('groupname', sa.String(length=64), nullable=True),
    sa.Column('code', sa.String(length=128), nullable=True),
    sa.Column('memberid', sa.Integer(), nullable=True),
    sa.Column('lastname', sa.String(length=64), nullable=True),
    sa.Column('lastname2', sa.String(length=64), nullable=True),
    sa.Column('middlename', sa.String(length=64), nullable=True),
    sa.Column('firstname', sa.String(length=64), nullable=True),
    sa.Column('address', sa.String(length=128), nullable=True),
    sa.Column('address2', sa.String(length=128), nullable=True),
    sa.Column('address3', sa.String(length=128), nullable=True),
    sa.Column('postalcode', sa.String(length=16), nullable=True),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.Column('state', sa.String(length=64), nullable=True),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('gender', sa.String(length=64), nullable=True),
    sa.Column('dob', sa.DateTime(), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('phone2', sa.String(length=64), nullable=True),
    sa.Column('mobile', sa.String(length=64), nullable=True),
    sa.Column('fax', sa.String(length=64), nullable=True),
    sa.Column('fax2', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('website', sa.String(length=128), nullable=True),
    sa.Column('categoryname', sa.String(length=64), nullable=True),
    sa.Column('startdate', sa.DateTime(), nullable=True),
    sa.Column('endate', sa.DateTime(), nullable=True),
    sa.Column('role', sa.String(length=64), nullable=True),
    sa.Column('PlayerLevelSingle', sa.String(length=2), nullable=True),
    sa.Column('PlayerLevelDouble', sa.String(length=2), nullable=True),
    sa.Column('PlayerLevelMixed', sa.String(length=2), nullable=True),
    sa.Column('TypeName', sa.String(length=64), nullable=True),
    sa.Column('Geen_Badminton_Magazine', sa.Boolean(), nullable=True),
    sa.Column('Handicap', sa.Boolean(), nullable=True),
    sa.Column('Nieuwsbrief', sa.Boolean(), nullable=True),
    sa.Column('Partners', sa.Boolean(), nullable=True),
    sa.Column('Betaald', sa.Boolean(), nullable=True),
    sa.Column('Betaald_bedrag', sa.Integer(), nullable=True),
    sa.Column('Datum_betaling', sa.DateTime(), nullable=True),
    sa.Column('Email_vader', sa.String(length=64), nullable=True),
    sa.Column('Email_moeder', sa.String(length=64), nullable=True),
    sa.Column('GSM_vader', sa.String(length=64), nullable=True),
    sa.Column('GSM_moeder', sa.String(length=64), nullable=True),
    sa.Column('Kyu', sa.String(length=64), nullable=True),
    sa.Column('Kyu_gaat_in_op', sa.DateTime(), nullable=True),
    sa.Column('Verwittiging', sa.Boolean(), nullable=True),
    sa.Column('PO_ID_VOTAS', sa.String(length=128), nullable=True),
    sa.Column('kapitein', sa.Boolean(), nullable=True),
    sa.Column('wedstrijdleider', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_speler_Betaald'), 'speler', ['Betaald'], unique=False)
    op.create_index(op.f('ix_speler_Betaald_bedrag'), 'speler', ['Betaald_bedrag'], unique=False)
    op.create_index(op.f('ix_speler_PlayerLevelDouble'), 'speler', ['PlayerLevelDouble'], unique=False)
    op.create_index(op.f('ix_speler_PlayerLevelMixed'), 'speler', ['PlayerLevelMixed'], unique=False)
    op.create_index(op.f('ix_speler_PlayerLevelSingle'), 'speler', ['PlayerLevelSingle'], unique=False)
    op.create_index(op.f('ix_speler_TypeName'), 'speler', ['TypeName'], unique=False)
    op.create_index(op.f('ix_speler_address'), 'speler', ['address'], unique=False)
    op.create_index(op.f('ix_speler_address2'), 'speler', ['address2'], unique=False)
    op.create_index(op.f('ix_speler_address3'), 'speler', ['address3'], unique=False)
    op.create_index(op.f('ix_speler_categoryname'), 'speler', ['categoryname'], unique=False)
    op.create_index(op.f('ix_speler_city'), 'speler', ['city'], unique=False)
    op.create_index(op.f('ix_speler_code'), 'speler', ['code'], unique=False)
    op.create_index(op.f('ix_speler_country'), 'speler', ['country'], unique=False)
    op.create_index(op.f('ix_speler_dob'), 'speler', ['dob'], unique=False)
    op.create_index(op.f('ix_speler_email'), 'speler', ['email'], unique=False)
    op.create_index(op.f('ix_speler_endate'), 'speler', ['endate'], unique=False)
    op.create_index(op.f('ix_speler_fax'), 'speler', ['fax'], unique=False)
    op.create_index(op.f('ix_speler_fax2'), 'speler', ['fax2'], unique=False)
    op.create_index(op.f('ix_speler_firstname'), 'speler', ['firstname'], unique=False)
    op.create_index(op.f('ix_speler_gender'), 'speler', ['gender'], unique=False)
    op.create_index(op.f('ix_speler_groupcode'), 'speler', ['groupcode'], unique=False)
    op.create_index(op.f('ix_speler_groupname'), 'speler', ['groupname'], unique=False)
    op.create_index(op.f('ix_speler_kapitein'), 'speler', ['kapitein'], unique=False)
    op.create_index(op.f('ix_speler_lastname'), 'speler', ['lastname'], unique=False)
    op.create_index(op.f('ix_speler_lastname2'), 'speler', ['lastname2'], unique=False)
    op.create_index(op.f('ix_speler_memberid'), 'speler', ['memberid'], unique=False)
    op.create_index(op.f('ix_speler_middlename'), 'speler', ['middlename'], unique=False)
    op.create_index(op.f('ix_speler_mobile'), 'speler', ['mobile'], unique=False)
    op.create_index(op.f('ix_speler_phone'), 'speler', ['phone'], unique=False)
    op.create_index(op.f('ix_speler_phone2'), 'speler', ['phone2'], unique=False)
    op.create_index(op.f('ix_speler_postalcode'), 'speler', ['postalcode'], unique=False)
    op.create_index(op.f('ix_speler_role'), 'speler', ['role'], unique=False)
    op.create_index(op.f('ix_speler_startdate'), 'speler', ['startdate'], unique=False)
    op.create_index(op.f('ix_speler_state'), 'speler', ['state'], unique=False)
    op.create_index(op.f('ix_speler_website'), 'speler', ['website'], unique=False)
    op.create_index(op.f('ix_speler_wedstrijdleider'), 'speler', ['wedstrijdleider'], unique=False)
    op.create_table('speler_ploeg',
    sa.Column('speler_id', sa.Integer(), nullable=False),
    sa.Column('ploeg_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ploeg_id'], ['ploeg.id'], ),
    sa.ForeignKeyConstraint(['speler_id'], ['speler.id'], ),
    sa.PrimaryKeyConstraint('speler_id', 'ploeg_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('speler_ploeg')
    op.drop_index(op.f('ix_speler_wedstrijdleider'), table_name='speler')
    op.drop_index(op.f('ix_speler_website'), table_name='speler')
    op.drop_index(op.f('ix_speler_state'), table_name='speler')
    op.drop_index(op.f('ix_speler_startdate'), table_name='speler')
    op.drop_index(op.f('ix_speler_role'), table_name='speler')
    op.drop_index(op.f('ix_speler_postalcode'), table_name='speler')
    op.drop_index(op.f('ix_speler_phone2'), table_name='speler')
    op.drop_index(op.f('ix_speler_phone'), table_name='speler')
    op.drop_index(op.f('ix_speler_mobile'), table_name='speler')
    op.drop_index(op.f('ix_speler_middlename'), table_name='speler')
    op.drop_index(op.f('ix_speler_memberid'), table_name='speler')
    op.drop_index(op.f('ix_speler_lastname2'), table_name='speler')
    op.drop_index(op.f('ix_speler_lastname'), table_name='speler')
    op.drop_index(op.f('ix_speler_kapitein'), table_name='speler')
    op.drop_index(op.f('ix_speler_groupname'), table_name='speler')
    op.drop_index(op.f('ix_speler_groupcode'), table_name='speler')
    op.drop_index(op.f('ix_speler_gender'), table_name='speler')
    op.drop_index(op.f('ix_speler_firstname'), table_name='speler')
    op.drop_index(op.f('ix_speler_fax2'), table_name='speler')
    op.drop_index(op.f('ix_speler_fax'), table_name='speler')
    op.drop_index(op.f('ix_speler_endate'), table_name='speler')
    op.drop_index(op.f('ix_speler_email'), table_name='speler')
    op.drop_index(op.f('ix_speler_dob'), table_name='speler')
    op.drop_index(op.f('ix_speler_country'), table_name='speler')
    op.drop_index(op.f('ix_speler_code'), table_name='speler')
    op.drop_index(op.f('ix_speler_city'), table_name='speler')
    op.drop_index(op.f('ix_speler_categoryname'), table_name='speler')
    op.drop_index(op.f('ix_speler_address3'), table_name='speler')
    op.drop_index(op.f('ix_speler_address2'), table_name='speler')
    op.drop_index(op.f('ix_speler_address'), table_name='speler')
    op.drop_index(op.f('ix_speler_TypeName'), table_name='speler')
    op.drop_index(op.f('ix_speler_PlayerLevelSingle'), table_name='speler')
    op.drop_index(op.f('ix_speler_PlayerLevelMixed'), table_name='speler')
    op.drop_index(op.f('ix_speler_PlayerLevelDouble'), table_name='speler')
    op.drop_index(op.f('ix_speler_Betaald_bedrag'), table_name='speler')
    op.drop_index(op.f('ix_speler_Betaald'), table_name='speler')
    op.drop_table('speler')
    op.drop_index(op.f('ix_ploeg_seizoen'), table_name='ploeg')
    op.drop_index(op.f('ix_ploeg_reeks'), table_name='ploeg')
    op.drop_index(op.f('ix_ploeg_ploegnaam'), table_name='ploeg')
    op.drop_table('ploeg')
    op.drop_index(op.f('ix_gebruiker_naam'), table_name='gebruiker')
    op.drop_index(op.f('ix_gebruiker_gebruikersnaam'), table_name='gebruiker')
    op.drop_table('gebruiker')
    # ### end Alembic commands ###
